all:
	g++ -l tiff -lm -w -std=c++11 -o main main.cpp

debug:
	g++ -l tiff -w -g -std=c++11 -o main main.cpp

nch:
	g++ -l tiff -lm -w -std=c++11 -o main_nch main_nch.cpp

debug_nch:
	g++ -l tiff -w -g -std=c++11 -o main_nch main_nch.cpp

clean:
	rm main
	rm main_nch
